apiVersion: v1
kind: Service
metadata:
  name: bird-api-service
spec:
  type: NodePort
  selector:
    app: bird-api
  ports:
  - protocol: TCP
    port: 30002
    nodePort: 30002
    targetPort: 5000