apiVersion: apps/v1
kind: Deployment
metadata:
  name: agn
  labels:
    app: agn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agn
  template:
    metadata:
      labels:
        app: agn
    spec:
      containers:
      - name: agn
        image: laundrybyte/agn:latest

---

apiVersion: v1
kind: Service
metadata:
  name: agn-service
spec:
  type: NodePort
  selector:
    app: agn
  ports:
  - protocol: TCP
    port: 30003
    nodePort: 30003
    targetPort: 80