apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitals
  labels:
    app: capitals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitals
  template:
    metadata:
      labels:
        app: capitals
    spec:
      containers:
      - name: capitals
        image: laundrybyte/capitals:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: capitals-service
spec:
  type: NodePort
  selector:
    app: capitals
  ports:
  - protocol: TCP
    port: 30012
    nodePort: 30012
    targetPort: 80
  
