apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-guesser
  labels:
    app: color-guesser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-guesser
  template:
    metadata:
      labels:
        app: color-guesser
    spec:
      containers:
      - name: color-guesser
        image: laundrybyte/color-guesser:latest

---

apiVersion: v1
kind: Service
metadata:
  name: color-guesser-service
spec:
  type: NodePort
  selector:
    app: color-guesser
  ports:
  - protocol: TCP
    port: 30001
    nodePort: 30001
    targetPort: 80