apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api
  labels:
    app: coordinates-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinates-api
  template:
    metadata:
      labels:
        app: coordinates-api
    spec:
      containers:
      - name: coordinates-api
        image: laundrybyte/coordinates-api:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-service
spec:
  type: NodePort
  selector:
    app: coordinates-api
  ports:
  - protocol: TCP
    port: 30005
    nodePort: 30005
    targetPort: 3000
  
