apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates
  labels:
    app: coordinates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinates
  template:
    metadata:
      labels:
        app: coordinates
    spec:
      containers:
      - name: coordinates
        image: laundrybyte/coordinates:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: coordinates-service
spec:
  type: NodePort
  selector:
    app: coordinates
  ports:
  - protocol: TCP
    port: 30006
    nodePort: 30006
    targetPort: 80
    