apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api-ex
  labels:
    app: coordinates-api-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinates-api-ex
  template:
    metadata:
      labels:
        app: coordinates-api-ex
    spec:
      containers:
      - name: coordinates-api-ex
        image: laundrybyte/coordinates-api-ex:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: coordinates-api-ex

---

apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-ex-service
spec:
  type: NodePort
  selector:
    app: coordinates-api-ex
  ports:
  - protocol: TCP
    port: 30006
    nodePort: 30006
    targetPort: 4000
  
