apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoly
  labels:
    app: demoly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoly
  template:
    metadata:
      labels:
        app: demoly
    spec:
      containers:
      - name: demoly
        image: laundrybyte/demoly:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: demoly-service
spec:
  type: NodePort
  selector:
    app: demoly
  ports:
  - protocol: TCP
    port: 30010
    nodePort: 30010
    targetPort: 80
  
