apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-api
  labels:
    app: fake-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-api
  template:
    metadata:
      labels:
        app: fake-api
    spec:
      containers:
      - name: fake-api
        image: laundrybyte/fake-api:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: fake-api-service
spec:
  type: NodePort
  selector:
    app: fake-api
  ports:
  - protocol: TCP
    port: 30011
    nodePort: 30011
    targetPort: 5000
  
