apiVersion: apps/v1
kind: Deployment
metadata:
  name: geojson-api
  labels:
    app: geojson-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geojson-api
  template:
    metadata:
      labels:
        app: geojson-api
    spec:
      containers:
      - name: geojson-api
        image: laundrybyte/geojson-api:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: geojson-api-service
spec:
  type: NodePort
  selector:
    app: geojson-api
  ports:
  - protocol: TCP
    port: 30004
    nodePort: 30004
    targetPort: 3000
  
