apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: laundrybyte/home:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  type: NodePort
  selector:
    app: home
  ports:
  - protocol: TCP
    port: 30003
    nodePort: 30003
    targetPort: 80