---
- name: copy secrets
  hosts: web
  become: yes
  remote_user: ubuntu
  become_user: root

  tasks:
  - name: create secrets directory
    file:
      path: /home/ubuntu/infra/secrets
      state: directory

  - name: copy secrets
    copy:
      src: ../../secrets
      dest: /home/ubuntu/infra

  - name: get secrets
    shell: ls /home/ubuntu/infra/secrets/*.env | xargs -n 1 basename | sed 's/\.env//g'
    register: secrets_list

  - name: create config maps
    shell: microk8s kubectl create secret generic {{ item }} --from-env-file=/home/ubuntu/infra/secrets/{{ item }}.env
    with_items: "{{ secrets_list.stdout_lines }}"