---
- name: fetch metrics
  hosts: web
  become: yes
  remote_user: ubuntu

  tasks:
  - name: get pods
    shell: microk8s kubectl get pods --no-headers | cut -d " " -f 1
    register: pods_list

  - name: create log file
    copy:
      dest: /tmp/resource_usage
      content: ''

  - name: pull resources
    shell: 'microk8s kubectl top pod {{ item }} --no-headers | sed -E "s/(\S+)\s+(\S+)\s+(\S+)/{\"pod\": \"\1\", \"cpu\": \"\2\", \"memory\": \"\3\"}/" >> /tmp/resource_usage'
    loop: "{{ pods_list.stdout_lines }}"
    changed_when: false

  - name: cat resource_usage
    shell: cat /tmp/resource_usage
    register: resource_usage

  - name: print resource usage
    debug:
      msg: "{{ resource_usage.stdout }}"