apiVersion: v1
kind: Service
metadata:
  name: color-guesser-service
spec:
  type: NodePort
  selector:
    app: color-guesser
  ports:
  - protocol: TCP
    port: 30021
    nodePort: 30001
    targetPort: 80